import { Pergunta } from "./pergunta.model";

export const Perguntas: Pergunta[] = [
    { id: 1, descricao: 'Síndrome de Down é doença?', resposta: false, 
    descricaoResposta: 'Mito! A síndrome de Down não é uma doença e não deve ser tratada como tal. É uma mutação cromossômica que afeta, em sua maioria, o cromossomo 21 causando a sua trissomia.'},
    { id: 2, descricao: 'Síndrome de Down tem cura?', resposta: false,
    descricaoResposta: 'Mito! A Síndrome de Down não é uma doença que através de intervenção cirúrgica, tratamento ou qualquer outro procedimento pode se modificar. Porém, diversas ações podem auxiliar no processo de estimulação dessas pessoas.'},
    { id: 3, descricao: 'Pessoas com Síndrome de Down falam e andam?', resposta: true,
    descricaoResposta: 'Verdade! A Síndrome de Down não possui ligação com a fala diretamente, portanto todas as crianças, se não apresentarem outro comprometimento, podem falar. Além disso, as crianças com Síndrome de Down conseguem andar, porém seu desenvolvimento motor apresenta um atraso em relação à maioria das crianças.'},
    { id: 4, descricao: 'Apenas pessoas brancas podem nascer com Síndrome de Down?', resposta: false,
    descricaoResposta: 'Mito! Por ser uma mutação cromossômica a síndrome de Down não possui relação alguma com a cor da pessoa.'},
    { id: 5, descricao: 'As pessoas com Síndrome de Down apresentam atraso no desenvolvimento da linguagem?', resposta: true,
    descricaoResposta: 'Verdade! Há um atraso no desenvolvimento da linguagem que pode ser observado ao longo da infância com surgimento das primeiras palavras, frases e na dificuldade para emitir alguns sons. Entretanto, depende das características de cada indivíduo.'},
    { id: 6, descricao: 'Pessoas com Síndrome de Down são agressivas?', resposta: false,
    descricaoResposta: 'Mito! Não podemos generalizar as pessoas com Síndrome de Down com base em determinados comportamentos pois, essa afirmação gera preconceito e estigma. Cada indivíduo tem suas características que devem ser percebidas na sua singularidade.'},
    { id: 7, descricao: 'Pessoas com Síndrome de Down adoecem mais?', resposta: true,
    descricaoResposta: 'Verdade! Ocasionalmente, como consequência da baixa resistência imunológica, as crianças com Síndrome de Down, principalmente nos primeiros anos de vida, são mais susceptíveis a infecções, principalmente no sistema respiratório e digestivo. Esta propensão vai diminuindo com o passar da idade.'},
    { id: 8, descricao: 'Pessoas com Síndrome de Down podem trabalhar?', resposta: true,
    descricaoResposta: 'Verdade! As pessoas com Síndrome de Down devem trabalhar pois, o trabalho é essencial para a construção de uma identidade adulta. O trabalho faz parte da sua realização pessoal e auxilia na estimulação dos sentidos. Atualmente, há muitas oportunidades de trabalho para as pessoas com deficiência devido às políticas públicas.'},
    { id: 9, descricao: 'Pessoas com Síndrome de Down devem frequentar escolas especiais?', resposta: false,
    descricaoResposta: 'Mito! As pessoas com síndrome de Down, assim como pessoas com qualquer tipo de deficiência, devem por lei frequentar o ensino regular e participar do Ensino Educacional Especializado no turno oposto.'},
    { id: 10, descricao: 'Pessoas com Síndrome de Down podem praticar esporte?', resposta: true,
    descricaoResposta: 'Verdade! As pessoas com Síndrome de Down devem praticar atividade física para seu bem-estar físico e emocional. A prática de atividades físicas deve ser realizada aonde for mais conveniente para a pessoa e sempre acompanhada por uma avaliação física antes do início de quaisquer atividades.'},
    { id: 11, descricao: 'Pessoas com Síndrome de Down têm a sexualidade mais aflorada?', resposta: false,
    descricaoResposta: 'Mito! Diante do fato de que recebem poucas informações sobre sexualidade e têm poucas oportunidades de socialização, a expressão considerada inadequada dos desejos sexuais nas pessoas com deficiência, refere-se à manifestação da sexualidade de um modo grosseiro que não correspondente às regras sociais e isso prejudica a imagem que as pessoas têm do deficiente que os colocam como dotados de uma sexualidade atípica. Desse modo o desejo, que é normal em todo ser humano, aparece como diferenciado e exagerado pela sua exteriorização inadequada.'},
    { id: 12, descricao: 'Pessoas com Síndrome de Down são assexuadas?', resposta: false,
    descricaoResposta: 'Mito! Ao considerar a pessoa com deficiência como alguém não dotado de sexualidade, negligenciam-se os cuidados contra situações de abuso e se omitem a essas pessoas o direito de acesso a orientação/educação sexual. Isso é um grave equívoco que tem elevado os índices de violência, de gravidez indesejada e doenças sexualmente transmissíveis.'},
  ];